env:
  global:
    - secure: Df80FE6VW8dCaqrfrQoA5wH2SdL/b3rDeNRXnmTJOBNvPvV7Bdtlvwtvtsw8ZEcENYd+RMn2XNrBbX2yA2cEV17BwcAZm4S4X4XvOsQIgHXNe573IgwuvtpzEyQwwnF6Eq56pI1jLw8AY6pyed2+Ehbj1HnA4ByOzADwl+kpP2Q=

language: rust
rust: nightly

script:
  - rustc --version
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - cargo doc --verbose

after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
